import type { AgentRole, ExecutionPipeline, ExpectedOutputs, IssueCategory, IssueDisplayStatus } from "./status";

export type V1Issue = {
  id: string;
  projectId?: string | null;
  milestoneId?: string | null;
  title: string;
  issueCategory?: IssueCategory;
  requiredAgentRole?: AgentRole;
  sourceSpecId?: string | null;
  sourceSpecPath?: string | null;
  issuePath?: string | null;
  createdAt?: number | null;
  updatedAt?: number | null;
  handoffId?: string | null;
  contextPackPath?: string | null;
  auditTrigger?: string | null;
  auditId?: string | null;
  sourceReleaseId?: string | null;
  sourceDeliveryPath?: string | null;
  auditOutputDir?: string | null;
  displayStatus?: IssueDisplayStatus;
  status: string;
  rawStatus: string;
  goal: string;
  scope: string[];
  nonGoals: string[];
  dependencies: string[];
  codexInstructions: string[];
  acceptanceCriteria: string[];
  validationCommands: string[];
  expectedOutputs: ExpectedOutputs;
  executionPipeline?: ExecutionPipeline | null;
  evidenceRequired: string[];
  allowedFiles: string[];
  forbiddenFiles: string[];
  forbiddenActions: string[];
  boundary: string[];
  priority: string;
  executionRisk: string;
};
