use agentflow_action_contract::ActionContractRegistry;
use agentflow_ontology::OntologyRegistry;

use crate::model::{
    ObjectStateDefinition, ObjectStateMachine, ObjectStateMachineBundle, ObjectStateMachineStatus,
    StateProjectionHints, StateTransitionDefinition, OBJECT_STATE_BUNDLE_VERSION,
};
use crate::registry::ObjectStateMachineRegistry;
use crate::report::ObjectStateValidationReport;

pub const CORE_OBJECT_STATE_ID: &str = "agentflow.object-state.core";
pub const CORE_OBJECT_STATE_NAMESPACE: &str = "agentflow.object-state.core";
pub const CORE_OBJECT_STATE_VERSION: &str = "v1-draft";
pub const CORE_OBJECT_STATE_REF: &str = "agentflow.object-state.core@v1-draft";

pub fn core_object_state_bundle() -> ObjectStateMachineBundle {
    ObjectStateMachineBundle {
        version: OBJECT_STATE_BUNDLE_VERSION.into(),
        registry_id: CORE_OBJECT_STATE_ID.into(),
        namespace: CORE_OBJECT_STATE_NAMESPACE.into(),
        definition_version: CORE_OBJECT_STATE_VERSION.into(),
        status: ObjectStateMachineStatus::Draft,
        state_machines: vec![
            requirement_state_machine(),
            spec_state_machine(),
            issue_state_machine(),
            run_state_machine(),
            audit_state_machine(),
            finding_state_machine(),
        ],
    }
}

pub fn core_object_state_registry(
    ontology_registry: &OntologyRegistry,
    action_registry: &ActionContractRegistry,
) -> Result<ObjectStateMachineRegistry, ObjectStateValidationReport> {
    ObjectStateMachineRegistry::load_bundle(
        core_object_state_bundle(),
        ontology_registry,
        action_registry,
    )
}

fn requirement_state_machine() -> ObjectStateMachine {
    machine(
        "requirement.state-machine",
        "Requirement",
        "captured",
        vec![
            state(
                "captured",
                "Captured",
                "已捕获原始意图。",
                false,
                false,
                vec![],
            ),
            state(
                "normalized",
                "Normalized",
                "已完成输入归一化。",
                false,
                false,
                vec![],
            ),
            state(
                "classified",
                "Classified",
                "已完成需求分类。",
                false,
                false,
                vec![],
            ),
            state(
                "needsClarification",
                "Needs Clarification",
                "存在阻断性歧义，等待人类补充。",
                false,
                true,
                vec!["needs-clarification"],
            ),
            state(
                "accepted",
                "Accepted",
                "已接受，可进入 Spec Loop。",
                false,
                false,
                vec!["ready-for-spec"],
            ),
            state(
                "rejected",
                "Rejected",
                "不进入后续流程。",
                true,
                false,
                vec![],
            ),
            state(
                "superseded",
                "Superseded",
                "已被新需求替代。",
                true,
                false,
                vec![],
            ),
        ],
        vec!["rejected", "superseded"],
        vec![
            transition(
                "capture",
                vec![],
                "captured",
                "captureRequirement",
                vec!["submitRequirement"],
                vec!["humanIntentPresent"],
                vec![],
                vec!["RequirementCaptured"],
                vec![],
                vec!["goal-agent", "spec-agent"],
            ),
            transition(
                "normalize",
                vec!["captured"],
                "normalized",
                "normalizeIntake",
                vec!["normalizeRequirement"],
                vec!["inputParsable"],
                vec![],
                vec!["RequirementNormalized"],
                vec![],
                vec!["spec-agent"],
            ),
            transition(
                "classify",
                vec!["normalized"],
                "classified",
                "classifyRequirement",
                vec!["classifyRequirement"],
                vec!["classificationComplete"],
                vec![],
                vec!["RequirementClassified"],
                vec![],
                vec!["spec-agent"],
            ),
            transition(
                "request-clarification",
                vec!["captured", "normalized", "classified"],
                "needsClarification",
                "requestClarification",
                vec!["recordDecision"],
                vec!["blockingAmbiguityPresent"],
                vec![],
                vec!["RequirementClarificationRequested"],
                vec![],
                vec!["spec-agent", "human-owner"],
            ),
            transition(
                "answer-clarification",
                vec!["needsClarification"],
                "normalized",
                "answerClarification",
                vec!["submitRequirement"],
                vec!["clarificationProvided"],
                vec![],
                vec!["RequirementClarificationAnswered"],
                vec![],
                vec!["human-owner", "spec-agent"],
            ),
            transition(
                "accept",
                vec!["classified"],
                "accepted",
                "acceptRequirement",
                vec!["recordDecision"],
                vec!["scopeIsClear"],
                vec![],
                vec!["RequirementAccepted"],
                vec![],
                vec!["human-owner"],
            ),
            transition(
                "reject",
                vec!["classified", "needsClarification"],
                "rejected",
                "rejectRequirement",
                vec!["recordDecision"],
                vec!["rejectionRecorded"],
                vec![],
                vec!["RequirementRejected"],
                vec![],
                vec!["human-owner"],
            ),
            transition(
                "supersede",
                vec!["accepted", "classified"],
                "superseded",
                "supersedeRequirement",
                vec!["recordDecision"],
                vec!["replacementRequirementExists"],
                vec![],
                vec!["RequirementSuperseded"],
                vec!["derivesFrom"],
                vec!["human-owner"],
            ),
        ],
        vec![
            "Requirement.accepted 才能进入 draftSpec。",
            "Requirement.rejected 不得继续派生 Spec。",
            "Requirement.superseded 必须保留替代关系。",
        ],
        hints(
            vec![
                "captured",
                "normalized",
                "classified",
                "needsClarification",
                "accepted",
                "rejected",
                "superseded",
            ],
            vec!["needsClarification", "accepted"],
        ),
    )
}

fn spec_state_machine() -> ObjectStateMachine {
    machine(
        "spec.state-machine",
        "Spec",
        "drafting",
        vec![
            state(
                "drafting",
                "Drafting",
                "Spec Agent 正在生成草案。",
                false,
                false,
                vec![],
            ),
            state(
                "draftReady",
                "Draft Ready",
                "草案已可预览。",
                false,
                false,
                vec![],
            ),
            state(
                "awaitingConfirmation",
                "Awaiting Confirmation",
                "等待人类确认。",
                false,
                true,
                vec!["awaiting-confirmation"],
            ),
            state(
                "changeRequested",
                "Change Requested",
                "人类要求调整。",
                false,
                true,
                vec!["change-requested"],
            ),
            state(
                "approved",
                "Approved",
                "已确认，可派生工作契约。",
                false,
                false,
                vec!["confirmed"],
            ),
            state(
                "cancelled",
                "Cancelled",
                "Spec 已取消。",
                true,
                false,
                vec!["cancel"],
            ),
            state(
                "superseded",
                "Superseded",
                "被新版 Spec 替代。",
                true,
                false,
                vec![],
            ),
        ],
        vec!["cancelled", "superseded"],
        vec![
            transition(
                "draft",
                vec![],
                "drafting",
                "draftSpec",
                vec!["draftSpec"],
                vec!["requirementAccepted"],
                vec![],
                vec!["SpecDraftingStarted"],
                vec!["derivesFrom"],
                vec!["spec-agent"],
            ),
            transition(
                "prepare-preview",
                vec!["drafting"],
                "draftReady",
                "prepareSpecPreview",
                vec!["draftSpec"],
                vec!["specFieldsComplete"],
                vec![],
                vec!["SpecPreviewPrepared"],
                vec![],
                vec!["spec-agent"],
            ),
            transition(
                "request-human-confirmation",
                vec!["draftReady"],
                "awaitingConfirmation",
                "requestHumanConfirmation",
                vec!["recordDecision"],
                vec!["previewReadable"],
                vec![],
                vec!["SpecConfirmationRequested"],
                vec![],
                vec!["spec-agent", "human-owner"],
            ),
            transition(
                "approve",
                vec!["awaitingConfirmation"],
                "approved",
                "approveSpec",
                vec!["approveSpec"],
                vec!["humanConfirmed"],
                vec!["humanConfirmation"],
                vec!["SpecApproved"],
                vec![],
                vec!["human-owner"],
            ),
            transition(
                "request-changes",
                vec!["awaitingConfirmation"],
                "changeRequested",
                "requestSpecChanges",
                vec!["recordDecision"],
                vec!["changeFeedbackRecorded"],
                vec![],
                vec!["SpecChangesRequested"],
                vec![],
                vec!["human-owner"],
            ),
            transition(
                "revise",
                vec!["changeRequested"],
                "drafting",
                "reviseSpec",
                vec!["draftSpec"],
                vec!["changeRequestExecutable"],
                vec![],
                vec!["SpecRevisionStarted"],
                vec![],
                vec!["spec-agent"],
            ),
            transition(
                "cancel",
                vec![
                    "drafting",
                    "draftReady",
                    "awaitingConfirmation",
                    "changeRequested",
                ],
                "cancelled",
                "cancelSpec",
                vec!["recordDecision"],
                vec!["cancellationRecorded"],
                vec![],
                vec!["SpecCancelled"],
                vec![],
                vec!["human-owner"],
            ),
            transition(
                "supersede",
                vec!["approved"],
                "superseded",
                "supersedeSpec",
                vec!["recordDecision"],
                vec!["replacementSpecExists"],
                vec![],
                vec!["SpecSuperseded"],
                vec!["derivesFrom"],
                vec!["human-owner"],
            ),
        ],
        vec![
            "Spec.approved 才能派生 Project / Issue。",
            "未确认的 Spec Preview 不授权 Work Agent 执行。",
            "Spec.cancelled 不得继续派生 Issue。",
        ],
        hints(
            vec![
                "drafting",
                "draftReady",
                "awaitingConfirmation",
                "changeRequested",
                "approved",
                "cancelled",
                "superseded",
            ],
            vec!["awaitingConfirmation", "approved"],
        ),
    )
}

fn issue_state_machine() -> ObjectStateMachine {
    machine(
        "issue.state-machine",
        "Issue",
        "proposed",
        vec![
            state(
                "proposed",
                "Proposed",
                "已生成但尚未激活。",
                false,
                false,
                vec!["backlog"],
            ),
            state(
                "ready",
                "Ready",
                "可执行。",
                false,
                false,
                vec!["todo", "ready-for-execute"],
            ),
            state(
                "blocked",
                "Blocked",
                "依赖或边界阻塞。",
                false,
                true,
                vec!["blocked"],
            ),
            state(
                "running",
                "Running",
                "有活跃 Run 正在执行。",
                false,
                false,
                vec!["in_progress", "in-progress"],
            ),
            state(
                "reviewReady",
                "Review Ready",
                "交付材料已准备好，等待接收或后续处理。",
                false,
                false,
                vec!["in_review", "in-review", "delivered"],
            ),
            state(
                "done",
                "Done",
                "工作契约已完成。",
                false,
                false,
                vec!["completed"],
            ),
            state(
                "reopened",
                "Reopened",
                "完成后被授权重开。",
                false,
                true,
                vec![],
            ),
            state(
                "cancelled",
                "Cancelled",
                "Issue 已取消。",
                true,
                false,
                vec!["cancel", "canceled"],
            ),
            state(
                "superseded",
                "Superseded",
                "Issue 已被替代。",
                true,
                false,
                vec![],
            ),
        ],
        vec!["cancelled", "superseded"],
        vec![
            transition(
                "create",
                vec![],
                "proposed",
                "createIssue",
                vec!["createIssue"],
                vec!["legalSourceObject"],
                vec![],
                vec!["IssueCreated"],
                vec!["contains"],
                vec!["spec-agent", "goal-agent"],
            ),
            transition(
                "activate",
                vec!["proposed"],
                "ready",
                "activateIssue",
                vec!["activateIssue"],
                vec!["dependenciesSatisfied", "boundaryClear"],
                vec![],
                vec!["IssueActivated"],
                vec![],
                vec!["work-agent", "coordinator-agent"],
            ),
            transition(
                "start-run",
                vec!["ready"],
                "running",
                "startRun",
                vec!["startRun"],
                vec!["noActiveRunLock"],
                vec![],
                vec!["IssueRunning", "RunStarted"],
                vec!["executes"],
                vec!["work-agent"],
            ),
            transition(
                "block",
                vec!["ready", "running"],
                "blocked",
                "blockIssue",
                vec!["recordDecision"],
                vec!["blockingConditionDetected"],
                vec![],
                vec!["IssueBlocked"],
                vec![],
                vec!["work-agent", "coordinator-agent", "human-owner"],
            ),
            transition(
                "unblock",
                vec!["blocked"],
                "ready",
                "unblockIssue",
                vec!["recordDecision"],
                vec!["blockingConditionCleared"],
                vec![],
                vec!["IssueUnblocked"],
                vec![],
                vec!["coordinator-agent", "human-owner"],
            ),
            transition(
                "submit-delivery",
                vec!["running"],
                "reviewReady",
                "submitDelivery",
                vec!["submitArtifact", "submitEvidence"],
                vec!["requiredEvidenceSatisfied"],
                vec![],
                vec!["IssueReviewReady"],
                vec!["produces", "supports"],
                vec!["work-agent", "delivery-agent"],
            ),
            transition(
                "mark-done",
                vec!["reviewReady"],
                "done",
                "markIssueDone",
                vec!["markIssueDone"],
                vec!["acceptanceSatisfied"],
                vec![
                    "implementationSummary",
                    "verificationLog",
                    "artifactSummary",
                ],
                vec!["IssueMarkedDone"],
                vec![],
                vec!["work-agent", "human-owner"],
            ),
            transition(
                "reopen",
                vec!["done"],
                "reopened",
                "reopenIssue",
                vec!["recordDecision"],
                vec!["reopenAuthorized"],
                vec![],
                vec!["IssueReopened"],
                vec!["requiresFix"],
                vec!["human-owner", "audit-agent"],
            ),
            transition(
                "reactivate",
                vec!["reopened"],
                "ready",
                "activateIssue",
                vec!["activateIssue"],
                vec!["reworkBoundaryClear"],
                vec![],
                vec!["IssueReactivated"],
                vec![],
                vec!["work-agent", "coordinator-agent"],
            ),
            transition(
                "cancel",
                vec!["proposed", "ready", "blocked", "reopened"],
                "cancelled",
                "cancelIssue",
                vec!["recordDecision"],
                vec!["cancellationRecorded"],
                vec![],
                vec!["IssueCancelled"],
                vec![],
                vec!["human-owner"],
            ),
            transition(
                "supersede",
                vec!["proposed", "ready", "blocked", "done"],
                "superseded",
                "supersedeIssue",
                vec!["recordDecision"],
                vec!["replacementIssueExists"],
                vec![],
                vec!["IssueSuperseded"],
                vec!["blocks"],
                vec!["human-owner"],
            ),
        ],
        vec![
            "Issue.ready 才能 startRun。",
            "Issue.running 表示存在 active Run。",
            "Issue.done 不自动创建 Audit。",
            "Issue.reopened 必须由 HumanOwner 或 Finding 触发。",
        ],
        hints(
            vec![
                "proposed",
                "ready",
                "blocked",
                "running",
                "reviewReady",
                "done",
                "reopened",
                "cancelled",
                "superseded",
            ],
            vec!["ready", "running", "reviewReady", "done"],
        ),
    )
}

fn run_state_machine() -> ObjectStateMachine {
    machine(
        "run.state-machine",
        "Run",
        "queued",
        vec![
            state(
                "queued",
                "Queued",
                "已排队，等待执行。",
                false,
                false,
                vec!["todo", "preflight", "planned", "checkpointed"],
            ),
            state(
                "started",
                "Started",
                "已开始执行。",
                false,
                false,
                vec!["running", "patching", "validating"],
            ),
            state(
                "awaitingInput",
                "Awaiting Input",
                "等待必要人类输入。",
                false,
                true,
                vec!["awaiting-input"],
            ),
            state("paused", "Paused", "执行已暂停。", false, true, vec![]),
            state(
                "blocked",
                "Blocked",
                "执行中遇到阻塞。",
                false,
                true,
                vec![],
            ),
            state(
                "failed",
                "Failed",
                "执行失败，可重试。",
                false,
                true,
                vec![],
            ),
            state(
                "completed",
                "Completed",
                "本次执行已完成。",
                false,
                false,
                vec!["completed"],
            ),
            state(
                "cancelled",
                "Cancelled",
                "本次执行已取消。",
                true,
                false,
                vec!["cancel", "canceled"],
            ),
        ],
        vec!["cancelled"],
        vec![
            transition(
                "enqueue",
                vec![],
                "queued",
                "enqueueRun",
                vec!["startRun"],
                vec!["issueReady"],
                vec![],
                vec!["RunQueued"],
                vec!["executes"],
                vec!["work-agent", "coordinator-agent"],
            ),
            transition(
                "start",
                vec!["queued"],
                "started",
                "startRun",
                vec!["startRun"],
                vec!["executionLockAcquired"],
                vec![],
                vec!["RunStarted"],
                vec!["executes"],
                vec!["work-agent"],
            ),
            transition(
                "request-input",
                vec!["started"],
                "awaitingInput",
                "requestRunInput",
                vec!["recordDecision"],
                vec!["missingRequiredInput"],
                vec![],
                vec!["RunInputRequested"],
                vec![],
                vec!["work-agent", "human-owner"],
            ),
            transition(
                "provide-input",
                vec!["awaitingInput"],
                "started",
                "provideRunInput",
                vec!["recordDecision"],
                vec!["inputProvided"],
                vec![],
                vec!["RunInputProvided"],
                vec![],
                vec!["human-owner", "work-agent"],
            ),
            transition(
                "pause",
                vec!["started"],
                "paused",
                "pauseRun",
                vec!["recordDecision"],
                vec!["pauseRequested"],
                vec![],
                vec!["RunPaused"],
                vec![],
                vec!["human-owner", "coordinator-agent"],
            ),
            transition(
                "resume-from-paused",
                vec!["paused"],
                "started",
                "resumeRun",
                vec!["recordDecision"],
                vec!["pauseReasonCleared"],
                vec![],
                vec!["RunResumed"],
                vec![],
                vec!["human-owner", "coordinator-agent"],
            ),
            transition(
                "block",
                vec!["started"],
                "blocked",
                "blockRun",
                vec!["recordDecision"],
                vec!["runtimeBlocked"],
                vec![],
                vec!["RunBlocked"],
                vec![],
                vec!["work-agent", "coordinator-agent"],
            ),
            transition(
                "resume-from-blocked",
                vec!["blocked"],
                "started",
                "resumeRun",
                vec!["recordDecision"],
                vec!["blockerCleared"],
                vec![],
                vec!["RunResumed"],
                vec![],
                vec!["work-agent", "coordinator-agent"],
            ),
            transition(
                "fail",
                vec!["started", "blocked"],
                "failed",
                "failRun",
                vec!["recordDecision"],
                vec!["failureEvidenceRecorded"],
                vec![],
                vec!["RunFailed"],
                vec!["supports"],
                vec!["work-agent"],
            ),
            transition(
                "retry",
                vec!["failed"],
                "queued",
                "retryRun",
                vec!["recordDecision"],
                vec!["retryPolicyAllows"],
                vec![],
                vec!["RunRetried"],
                vec![],
                vec!["coordinator-agent", "human-owner"],
            ),
            transition(
                "complete",
                vec!["started"],
                "completed",
                "completeRun",
                vec!["submitArtifact", "submitEvidence"],
                vec!["deliveryAndEvidenceComplete"],
                vec![],
                vec!["RunCompleted"],
                vec!["produces", "supports"],
                vec!["work-agent", "delivery-agent"],
            ),
            transition(
                "cancel",
                vec![
                    "queued",
                    "started",
                    "awaitingInput",
                    "paused",
                    "blocked",
                    "failed",
                ],
                "cancelled",
                "cancelRun",
                vec!["recordDecision"],
                vec!["cancellationRecorded"],
                vec![],
                vec!["RunCancelled"],
                vec![],
                vec!["human-owner", "coordinator-agent"],
            ),
        ],
        vec![
            "Run.completed 不等于 Issue.done。",
            "Run.failed 必须保留失败 evidence。",
            "Run.cancelled 必须释放执行锁。",
        ],
        hints(
            vec![
                "queued",
                "started",
                "awaitingInput",
                "paused",
                "blocked",
                "failed",
                "completed",
                "cancelled",
            ],
            vec!["queued", "started", "completed"],
        ),
    )
}

fn audit_state_machine() -> ObjectStateMachine {
    machine(
        "audit.state-machine",
        "Audit",
        "requested",
        vec![
            state(
                "requested",
                "Requested",
                "已收到独立审计请求。",
                false,
                false,
                vec![],
            ),
            state(
                "accepted",
                "Accepted",
                "审计范围已确认。",
                false,
                false,
                vec![],
            ),
            state(
                "running",
                "Running",
                "Audit Agent 正在审计。",
                false,
                false,
                vec!["in_progress", "in-progress"],
            ),
            state(
                "reportReady",
                "Report Ready",
                "审计报告已生成。",
                false,
                false,
                vec!["report-ready"],
            ),
            state(
                "closed",
                "Closed",
                "审计流程已关闭。",
                true,
                false,
                vec!["done"],
            ),
            state(
                "cancelled",
                "Cancelled",
                "审计流程已取消。",
                true,
                false,
                vec!["cancel", "canceled"],
            ),
        ],
        vec!["closed", "cancelled"],
        vec![
            transition(
                "request",
                vec![],
                "requested",
                "requestAudit",
                vec!["requestAudit"],
                vec!["explicitAuditRequest"],
                vec!["humanConfirmation"],
                vec!["AuditRequested"],
                vec!["reviews"],
                vec!["human-owner"],
            ),
            transition(
                "accept",
                vec!["requested"],
                "accepted",
                "acceptAudit",
                vec!["recordDecision"],
                vec!["auditScopeConfirmed"],
                vec![],
                vec!["AuditAccepted"],
                vec![],
                vec!["human-owner", "audit-agent"],
            ),
            transition(
                "start",
                vec!["accepted"],
                "running",
                "startAudit",
                vec!["requestAudit"],
                vec!["auditRoleAuthorized"],
                vec![],
                vec!["AuditStarted"],
                vec!["reviews"],
                vec!["audit-agent"],
            ),
            transition(
                "submit-report",
                vec!["running"],
                "reportReady",
                "submitAuditReport",
                vec!["submitArtifact"],
                vec!["reportAndFindingsRecorded"],
                vec![],
                vec!["AuditReportSubmitted"],
                vec!["reviews"],
                vec!["audit-agent"],
            ),
            transition(
                "close",
                vec!["reportReady"],
                "closed",
                "closeAudit",
                vec!["recordDecision"],
                vec!["closeReasonRecorded"],
                vec![],
                vec!["AuditClosed"],
                vec![],
                vec!["human-owner"],
            ),
            transition(
                "cancel",
                vec!["requested", "accepted", "running"],
                "cancelled",
                "cancelAudit",
                vec!["recordDecision"],
                vec!["cancellationRecorded"],
                vec![],
                vec!["AuditCancelled"],
                vec![],
                vec!["human-owner"],
            ),
        ],
        vec![
            "Audit.requested 只能来自显式 requestAudit。",
            "Issue.done 不自动转成 Audit.requested。",
            "Audit 不修改 Build 交付事实。",
        ],
        hints(
            vec![
                "requested",
                "accepted",
                "running",
                "reportReady",
                "closed",
                "cancelled",
            ],
            vec!["requested", "running", "reportReady"],
        ),
    )
}

fn finding_state_machine() -> ObjectStateMachine {
    machine(
        "finding.state-machine",
        "Finding",
        "open",
        vec![
            state("open", "Open", "发现已创建。", false, false, vec![]),
            state("triaged", "Triaged", "已分类和定级。", false, false, vec![]),
            state(
                "fixRequired",
                "Fix Required",
                "需要修复。",
                false,
                true,
                vec![],
            ),
            state(
                "notActionable",
                "Not Actionable",
                "证据不足或无需行动。",
                false,
                false,
                vec!["dismissed"],
            ),
            state(
                "fixLinked",
                "Fix Linked",
                "已链接修复 Issue。",
                false,
                false,
                vec![],
            ),
            state(
                "resolved",
                "Resolved",
                "修复交付已提交。",
                false,
                false,
                vec![],
            ),
            state("verified", "Verified", "修复已验证。", false, false, vec![]),
            state(
                "closed",
                "Closed",
                "Finding 已关闭。",
                true,
                false,
                vec!["done"],
            ),
            state(
                "reopened",
                "Reopened",
                "Finding 被重开。",
                false,
                true,
                vec![],
            ),
        ],
        vec!["closed"],
        vec![
            transition(
                "create",
                vec![],
                "open",
                "createFinding",
                vec!["createFinding"],
                vec!["auditOrReviewSourcePresent"],
                vec!["auditReport"],
                vec!["FindingCreated"],
                vec!["reviews"],
                vec!["audit-agent", "review-agent"],
            ),
            transition(
                "triage",
                vec!["open", "reopened"],
                "triaged",
                "triageFinding",
                vec!["recordDecision"],
                vec!["classificationComplete"],
                vec![],
                vec!["FindingTriaged"],
                vec![],
                vec!["audit-agent", "review-agent"],
            ),
            transition(
                "require-fix",
                vec!["triaged"],
                "fixRequired",
                "requireFix",
                vec!["recordDecision"],
                vec!["repairNeeded"],
                vec![],
                vec!["FindingFixRequired"],
                vec!["requiresFix"],
                vec!["audit-agent", "review-agent"],
            ),
            transition(
                "dismiss",
                vec!["triaged"],
                "notActionable",
                "dismissFinding",
                vec!["recordDecision"],
                vec!["dismissalRecorded"],
                vec![],
                vec!["FindingDismissed"],
                vec![],
                vec!["audit-agent", "review-agent", "human-owner"],
            ),
            transition(
                "link-fix-issue",
                vec!["fixRequired"],
                "fixLinked",
                "linkFixIssue",
                vec!["linkFixIssue"],
                vec!["fixIssueExists"],
                vec![],
                vec!["FindingFixIssueLinked"],
                vec!["requiresFix"],
                vec!["audit-agent", "review-agent"],
            ),
            transition(
                "resolve",
                vec!["fixLinked"],
                "resolved",
                "markFindingResolved",
                vec!["submitArtifact"],
                vec!["repairIssueDelivered"],
                vec![],
                vec!["FindingResolved"],
                vec!["supports"],
                vec!["audit-agent", "review-agent"],
            ),
            transition(
                "verify-fix",
                vec!["resolved"],
                "verified",
                "verifyFindingFix",
                vec!["submitEvidence"],
                vec!["verificationPassed"],
                vec!["verificationLog"],
                vec!["FindingVerified"],
                vec!["supports"],
                vec!["audit-agent", "review-agent"],
            ),
            transition(
                "close",
                vec!["verified", "notActionable"],
                "closed",
                "closeFinding",
                vec!["recordDecision"],
                vec!["closeReasonRecorded"],
                vec![],
                vec!["FindingClosed"],
                vec![],
                vec!["human-owner", "audit-agent"],
            ),
            transition(
                "reopen",
                vec!["closed", "resolved", "verified"],
                "reopened",
                "reopenFinding",
                vec!["recordDecision"],
                vec!["newEvidenceOrVerificationFailed"],
                vec![],
                vec!["FindingReopened"],
                vec![],
                vec!["audit-agent", "review-agent", "human-owner"],
            ),
        ],
        vec![
            "Finding.fixRequired 可以派生或链接修复 Issue。",
            "Finding 不直接修改 Issue.done。",
            "Finding.closed 必须可追溯到验证证据或关闭决策。",
        ],
        hints(
            vec![
                "open",
                "triaged",
                "fixRequired",
                "notActionable",
                "fixLinked",
                "resolved",
                "verified",
                "closed",
                "reopened",
            ],
            vec!["fixRequired", "resolved", "verified"],
        ),
    )
}

fn machine(
    state_machine_id: &str,
    object_type: &str,
    initial_state: &str,
    states: Vec<ObjectStateDefinition>,
    terminal_states: Vec<&str>,
    transitions: Vec<StateTransitionDefinition>,
    invariants: Vec<&str>,
    projection_hints: StateProjectionHints,
) -> ObjectStateMachine {
    ObjectStateMachine {
        state_machine_id: state_machine_id.into(),
        object_type: object_type.into(),
        namespace: CORE_OBJECT_STATE_NAMESPACE.into(),
        version: CORE_OBJECT_STATE_VERSION.into(),
        status: ObjectStateMachineStatus::Draft,
        initial_state: initial_state.into(),
        states,
        terminal_states: terminal_states.into_iter().map(str::to_string).collect(),
        transitions,
        invariants: invariants.into_iter().map(str::to_string).collect(),
        projection_hints,
    }
}

fn state(
    state_id: &str,
    name: &str,
    description: &str,
    is_terminal: bool,
    is_error_state: bool,
    legacy_status_aliases: Vec<&str>,
) -> ObjectStateDefinition {
    ObjectStateDefinition {
        state_id: state_id.into(),
        name: name.into(),
        description: description.into(),
        is_terminal,
        is_error_state,
        legacy_status_aliases: legacy_status_aliases
            .into_iter()
            .map(str::to_string)
            .collect(),
    }
}

#[allow(clippy::too_many_arguments)]
fn transition(
    transition_id: &str,
    from_states: Vec<&str>,
    to_state: &str,
    action_type: &str,
    compatibility_action_aliases: Vec<&str>,
    guards: Vec<&str>,
    required_evidence: Vec<&str>,
    emitted_events: Vec<&str>,
    link_effects: Vec<&str>,
    role_hints: Vec<&str>,
) -> StateTransitionDefinition {
    StateTransitionDefinition {
        transition_id: transition_id.into(),
        from_states: from_states.into_iter().map(str::to_string).collect(),
        to_state: to_state.into(),
        action_type: action_type.into(),
        compatibility_action_aliases: compatibility_action_aliases
            .into_iter()
            .map(str::to_string)
            .collect(),
        guards: guards.into_iter().map(str::to_string).collect(),
        required_evidence: required_evidence.into_iter().map(str::to_string).collect(),
        emitted_events: emitted_events.into_iter().map(str::to_string).collect(),
        link_effects: link_effects.into_iter().map(str::to_string).collect(),
        role_hints: role_hints.into_iter().map(str::to_string).collect(),
    }
}

fn hints(timeline_order: Vec<&str>, preferred_current_states: Vec<&str>) -> StateProjectionHints {
    StateProjectionHints {
        timeline_order: timeline_order.into_iter().map(str::to_string).collect(),
        preferred_current_states: preferred_current_states
            .into_iter()
            .map(str::to_string)
            .collect(),
    }
}
